# fly.toml app configuration file generated for archaeopteryx on 2025-10-18T11:20:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'archaeopteryx'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = 'rolling'
  max_unavailable = 1

[env]
  ATPROTO_SERVICE_URL = 'https://bsky.social'
  HOSTNAME = '0.0.0.0'
  LOG_LEVEL = 'info'
  PORT = '8080'
  PUBLIC_URL = 'https://archaeopteryx.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  # Liveness check - checks if the service is alive
  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/health'
    type = 'http'

[[vm]]
  size = 'shared-cpu-1x'

# Metrics endpoint disabled in health checks
# The /metrics endpoint exists but isn't used for health monitoring
# [[metrics]]
#   port = 8080
#   path = '/metrics'
