name: Docker Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/docker.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Swiftly
        run: |
          curl -L https://swift-server.github.io/swiftly/swiftly-install.sh | bash -s -- -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Swift 6.2 with Swiftly
        run: |
          swiftly install 6.2
          swiftly use 6.2

      - name: Build Linux binary with Swift
        run: swift build -c release

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: archaeopteryx:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run --rm archaeopteryx:${{ github.sha }} ./Archaeopteryx --help || true
